spring.application.name=back-end
spring.data.mongodb.uri=mongodb://alunoueg:aluno%40ueg@179.255.33.190:4200/dbbackend
#COLOQUE_SUA_URI_MONGODB_AQUI
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.data.mongodb.type-key=_


